export default {
  async fetch(request, env) {
    const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"};
    if(request.method==="OPTIONS") return new Response(null,{headers:cors});
    await env.DB.prepare("CREATE TABLE IF NOT EXISTS staff (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, phone TEXT, age TEXT, experience TEXT, address TEXT)").run();
    const url = new URL(request.url);
    if(url.pathname==="/api/kormi"){
      const h={...cors,"Content-Type":"application/json"};
      if(request.method==="GET"){const {results}=await env.DB.prepare("SELECT * FROM staff ORDER BY id DESC").all();return new Response(JSON.stringify(results),{headers:h});}
      if(request.method==="POST"){const d=await request.json();await env.DB.prepare("INSERT INTO staff (name, phone, age, experience, address) VALUES (?,?,?,?,?)").bind(d.name||'',d.phone||'',d.age||'',d.experience||'',d.address||'').run();return new Response(JSON.stringify({success:true}),{headers:h});}
    }
    const html = `<!DOCTYPE html><html lang="bn"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width"><title>Prasenjit Shop - db</title><style>*{margin:0;padding:0;box-sizing:border-box;font-family:sans-serif}header{background:#111;color:#fff;padding:12px 16px;display:flex;justify-content:space-between;position:sticky;top:0}header a{background:#ffeb3b;color:#000;padding:6px 14px;border-radius:20px;text-decoration:none;font-weight:bold}main{padding:16px}.form{background:#f2f2f2;padding:14px;border-radius:12px;margin:16px 0}input,textarea{width:100%;padding:10px;margin:6px 0;border:1px solid #ccc;border-radius:8px}button{width:100%;padding:12px;background:#000;color:#fff;border:0;border-radius:8px}.card{border:1px solid #ddd;padding:12px;border-radius:10px;margin:8px 0}</style></head><body><header><h3>Prasenjit Shop - db Live</h3><a href="#kormi">কর্মী চাই</a></header><main><h2>db কানেক্টেড - D9A1</h2><p>ছোট হাতের db চলছে, prasenjit-shop-api এর সম্পর্ক নেই।</p><div id="kormi" style="margin-top:28px"><h2>কর্মী ফর্ম</h2><div class="form"><input id="n" placeholder="নাম"><input id="p" placeholder="ফোন"><input id="a" placeholder="বয়স"><input id="e" placeholder="অভিজ্ঞতা"><textarea id="ad" placeholder="ঠিকানা"></textarea><button onclick="add()">জমা দিন</button></div><div id="list"></div></div></main><script>const API="/api/kormi";async function load(){let r=await fetch(API);let d=await r.json();document.getElementById('list').innerHTML=d.map(s=>'<div class=card><b>'+s.name+'</b> ('+s.age+') - '+s.phone+'<br>'+s.experience+'<br>'+s.address+'</div>').join('')}async function add(){let o={name:n.value,phone:p.value,age:a.value,experience:e.value,address:ad.value};await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)});n.value=p.value=a.value=e.value=ad.value='';load();alert('সেভ হয়েছে db তে')}load();</script></body></html>`;
    return new Response(html,{headers:{"Content-Type":"text/html; charset=utf-8",...cors}});
  }
}
